### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by ayungavis** [dooboolab/prisma-offset-pagination#1]
Hi, I'm interested about your pagination system using prisma and I want to add it in my project, but when I tried to install it the response is `package not found`. Can you solve it?

## What I use?
I use node version `v14.13.1` and yarn version `1.22.5`

## Error log
```
Error: https://registry.yarnpkg.com/prisma-offset-pagination: Not found
      at Request.params.callback [as _callback] (/home/ayungavis/.config/yarn/global/node_modules/yarn/lib/cli.js:66988:18)
      at Request.self.callback (/home/ayungavis/.config/yarn/global/node_modules/yarn/lib/cli.js:140662:22)
      at Request.emit (events.js:314:20)
      at Request.<anonymous> (/home/ayungavis/.config/yarn/global/node_modules/yarn/lib/cli.js:141634:10)
      at Request.emit (events.js:314:20)
      at IncomingMessage.<anonymous> (/home/ayungavis/.config/yarn/global/node_modules/yarn/lib/cli.js:141556:12)
      at Object.onceWrapper (events.js:420:28)
      at IncomingMessage.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1252:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by ayungavis** [comment]
Thank you for publishing the package to NPM, I think it has solved the issue, so I will close this.
NPM package reference ([prisma-offset-pagination](https://www.npmjs.com/package/prisma-offset-pagination))
